import turtle

window = turtle.Turtle()
turtle.bgcolor("black")
window.speed(10)
window.fillcolor("#9b0000")
window.begin_fill()
window.pencolor("#9b0000")
window.forward(40)
window.left(90)
window.forward(90)
window.left(30)
window.forward(100)
window.left(140)
window.forward(180)
window.goto(0,180)
window.left(30)
window.end_fill()
window.forward(215)
turtle.done()