import turtle

window = turtle.Turtle()
turtle.bgcolor("black")
window.pencolor("black")
window.fillcolor("#00A4EF")
window.begin_fill()
window.pencolor("#00A4EF")
window.left(12)
window.forward(200)
window.right(102)
window.forward(250)
window.right(102)
window.forward(200)
window.right(78)
window.forward(170)
window.end_fill()
window.penup()
window.right(78)
window.forward(90)
window.pendown()
window.pensize(5)
window.pencolor("black")
window.right(102)
window.forward(215)
window.penup()
window.left(78)
window.forward(110)
window.left(102)
window.forward(130)
window.pendown()
window.left(90)
window.forward(195)

turtle.done()